name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]
    
    steps:
      # Step 3: Checkout Code - 
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 4: Set Up Node.js - 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 5: Print Environment Secrets - 
      - name: Print Env Secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "Checking if secrets are loaded..."
          echo "Secrets are masked by GitHub for security: $MONGO_URI"

      # Step 6: Stop Running Services in AWS - 
      - name: Stop Running Services in AWS
        run: pm2 stop all || true

      # Step 7: Install Backend Dependencies -
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Step 8: Install Frontend Dependencies and Build - 
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm install
          CI=false npm run build

      # Step 9: Run Backend Tests - 
      - name: Run Backend Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./backend
        run: npm test || echo "No tests defined, skipping..."

# Step 11: Create .env File and Add Secrets
      - name: Create .env File and Add Secrets
        run: |
          cd backend
          cat << 'EOF' > .env
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          PORT=${{ secrets.PORT }}
          EOF

      # Step 12: Start and Restart Services in AWS
      - name: Start and Restart Services in AWS
        run: |
          cd backend
          pm2 delete "meetup-backend" || true
          pm2 start server.js --name "meetup-backend" --update-env
          pm2 save

